# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e0930b9344f25e9f0f03142859921db3176271b1ea683c48209ef52ed06675834caf5b0b1b63e5a30236959e94884d4e45fc1efc8ee89c53ba3c47be6e52eaa

test:
  secret_key_base: dc90f49c93d17a46d501289a4b15421f0f01a34c48a95dd2787f64ebb5752deae637ce4ff1877b85b68058643ea2e32163fc5684c3294b2f889c7e05b0f0baa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
